# Generated by Django 5.2.1 on 2025-07-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_variationoption_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
    ]
