# Generated by Django 5.2.1 on 2025-07-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_price_product_var'),
        ('stock', '0002_alter_inventory_product_var'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariationOption',
            new_name='SubVariation',
        ),
        migrations.RenameModel(
            old_name='ProductVariant',
            new_name='Variation',
        ),
    ]
