# Generated by Django 5.2.1 on 2025-07-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_slug_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubVariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subvariation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subvariation', to='products.subvariationtype'),
            preserve_default=False,
        ),
    ]
