# Generated by Django 5.2.1 on 2025-07-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_subvariationtype_subvariation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvariationtype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
