# Generated by Django 5.2.1 on 2025-05-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(max_length=255)),
                ('long_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/')),
                ('slug', models.SlugField(unique=True)),
                ('marketing_price', models.FloatField()),
                ('marketing_promotional_price', models.FloatField(default=0.0)),
                ('product_type', models.CharField(choices=[('V', 'Variable'), ('S', 'Simple')], default='S', max_length=1)),
            ],
        ),
    ]
