# Generated by Django 5.2.1 on 2025-07-12 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_var', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.variationoption')),
            ],
        ),
    ]
