# Generated by Django 5.2.1 on 2025-07-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_price_product_var'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_var',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
    ]
