# Generated by Django 5.2.1 on 2025-07-07 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('public_id', models.UUIDField(unique=True)),
                ('expires_at', models.DateField()),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guest_public_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guest_public_id_expires_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
