# Generated by Django 5.2.1 on 2025-07-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_anonymousprofile_remove_profile_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
